// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvve8rnXiUA824Ag0G67MO2nPRxW0m5Ao',
    appId: '1:762750075229:web:5260a35cd312f11586a8b4',
    messagingSenderId: '762750075229',
    projectId: 'flutterfire-test-20225241',
    authDomain: 'flutterfire-test-20225241.firebaseapp.com',
    storageBucket: 'flutterfire-test-20225241.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHg5e9ib1xGg6wSkLeqWruQFmLgz_6V-k',
    appId: '1:762750075229:android:e7a2821569cb2f6486a8b4',
    messagingSenderId: '762750075229',
    projectId: 'flutterfire-test-20225241',
    storageBucket: 'flutterfire-test-20225241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUKNXt6q4pAztzcp_Wln9EFwWVbO_glY',
    appId: '1:762750075229:ios:b8ba58c14cb7362f86a8b4',
    messagingSenderId: '762750075229',
    projectId: 'flutterfire-test-20225241',
    storageBucket: 'flutterfire-test-20225241.firebasestorage.app',
    iosBundleId: 'com.example.wateringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUKNXt6q4pAztzcp_Wln9EFwWVbO_glY',
    appId: '1:762750075229:ios:b8ba58c14cb7362f86a8b4',
    messagingSenderId: '762750075229',
    projectId: 'flutterfire-test-20225241',
    storageBucket: 'flutterfire-test-20225241.firebasestorage.app',
    iosBundleId: 'com.example.wateringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvve8rnXiUA824Ag0G67MO2nPRxW0m5Ao',
    appId: '1:762750075229:web:c552cd5cd73a8aef86a8b4',
    messagingSenderId: '762750075229',
    projectId: 'flutterfire-test-20225241',
    authDomain: 'flutterfire-test-20225241.firebaseapp.com',
    storageBucket: 'flutterfire-test-20225241.firebasestorage.app',
  );
}
